const GRAND_HOTELL_BOOKING_URL = 'https://app.mews.com/distributor/f5520563-43b7-46f2-9ff9-b26b00b318ae?mewsAvailabilityBlockId=b9a3b275-880b-4157-8bb5-b47c00966c73&mewsStart=2027-06-11&mewsEnd=2027-06-13';
const SCANDIC_LUGNET_URL = 'https://www.scandichotels.se/hotell/sverige/falun/scandic-lugnet-falun';
// PLACEHOLDER: hotellet verkar ha bytt varumärke (dyker upp både som "Home Hotel Bergmästaren" och
// "Clarion Collection Hotel Bergmästaren" i sökresultat) — osäkert vilken som är aktuell officiell sajt.
// Bekräfta rätt namn/URL innan lansering.
const BERGMASTAREN_URL = 'https://BEKRAFTA-URL-HOTELL-BERGMASTAREN.se';
const stays = [['Grand Hotell', 'Klassiskt och centralt i Falun. Vi har förhandlat fram 20% rabatt till våra gäster.', null, <><a className="btn card__book" href={GRAND_HOTELL_BOOKING_URL} target="_blank" rel="noopener noreferrer">Boka med bröllopsrabatt</a><p className="card__book-hint">Länken är förifylld med bröllopshelgens datum och er rabatt.</p></>], ['Scandic Lugnet', 'Hotell i området Lugnet (idrottsarenan) i Falun. Ca 10 min promenad från bröllopslokalen.', <a className="inline" href={SCANDIC_LUGNET_URL} target="_blank" rel="noopener noreferrer">Boka via scandichotels.se</a>], ['Hotell Bergmästaren', 'Litet centralt hotell i Falun som ligger granne med Grand. Ca 15 min promenad från bröllopslokalen.', <a className="inline" href={BERGMASTAREN_URL} target="_blank" rel="noopener noreferrer">Besök hotellets webbplats</a>]];
function Cards({ items }) { return <div className="cards">{items.map(([title, text, meta, extra]) => <article className={`card${extra ? ' card--rec' : ''}`} key={title}>{extra && <span className="rec-badge">Bröllopsrabatt</span>}<div className="ico">♡</div><h3>{title}</h3><p>{text}</p>{meta && <div className="meta"><span>{meta}</span></div>}{extra}</article>)}</div>; }
// FÖRSLAG på klädkodspaletter — vägledande inspiration, inte fastställda. Brudparet väljer/justerar de faktiska tonerna.
const FRIDAY_PALETTE = [['#A7B795', 'Salvia'], ['#D9C6A3', 'Sand'], ['#C98A63', 'Terrakotta'], ['#E7DCC2', 'Lin']];
const SATURDAY_PALETTE = [['#2A3826', 'Mörkgrön'], ['#26344A', 'Marinblå'], ['#33352F', 'Antracit'], ['#9A7B45', 'Mässing']];
function Swatches({ palette }) { return <div className="dress-swatches">{palette.map(([color, label]) => <div className="swatch" key={label}><span className="chip" style={{ background: color }} /><span>{label}</span></div>)}</div>; }
export default function Information() { return <><section id="boende"><div className="wrap"><div className="section-head"><p className="kicker">Boende & tips</p><h2>Övernattning i Falun</h2><p className="lead">För er som behöver boende under helgen har vi listat några förslag, men vi rekommenderar varmt Grand Hotell. Hotellet ligger centralt i Falun och 15 minuters promenad från bröllopslokalen.</p><p className="lead">Klickar ni på länken nedan kommer ni till vår bokningssida som ger er 20 % rabatt vid bokning av hotellrum.</p></div><Cards items={stays} /><p className="venue-note">Har ni frågor eller funderingar gällande boende är det bara att ni hör av er till någon av oss så hjälper vi gärna er.</p></div></section><section className="alt" id="info"><div className="wrap split"><div className="split__media ph framed"><span>Foto · stämning & detaljer</span></div><div><p className="kicker">Klädkod</p><h2>Högtidligt & festklätt</h2><p className="dress-copy">Fredag – Sommarfin</p><p className="swatch-caption">Några toner som inspiration om ni vill ha en fingervisning — helt frivilligt att följa.</p><Swatches palette={FRIDAY_PALETTE} /><p className="dress-copy">Lördag – Mörk kostym</p><p className="swatch-caption">Ett par toner som kompletterar en mörk kostym, som förslag snarare än krav.</p><Swatches palette={SATURDAY_PALETTE} /><p className="dress-copy">Festen rör sig delvis utomhus, så ta med något varmt och skor som klarar gräs.</p></div></div></section><section id="gavor"><div className="wrap"><div className="section-head"><p className="kicker">Gåvor & önskelista</p><h2>Det finaste är att ni kommer</h2><p className="lead">Er närvaro är den största gåvan. Men för er som ändå vill ge något, önskar vi oss ett bidrag till vår bröllopsresa. Swisha till: 076-723 06 08</p></div></div></section></>; }
