import { useState } from 'react';

// Replace this with the deployed Google Apps Script Web App URL before publishing.
const GOOGLE_SHEET_ENDPOINT = 'https://script.google.com/macros/s/REPLACE_WITH_YOUR_DEPLOYMENT_ID/exec';
const initialForm = { name: '', attending: 'ja', mealChoice: '', notes: '' };

export default function RSVPForm() {
  const [form, setForm] = useState(initialForm); const [status, setStatus] = useState('idle');
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  const submit = async (event) => { event.preventDefault(); setStatus('sending'); try { const response = await fetch(GOOGLE_SHEET_ENDPOINT, { method: 'POST', body: JSON.stringify(form), headers: { 'Content-Type': 'text/plain;charset=utf-8' } }); if (!response.ok) throw new Error('Request failed'); setStatus('success'); setForm(initialForm); } catch { setStatus('error'); } };
  return <section className="rsvp" id="osa"><div className="wrap"><div className="section-head"><p className="kicker">OSA</p><h2>Kommer ni?</h2><div className="divider"><span className="mark" /></div><p className="lead">Fyll i formuläret per person och svara senast <strong>1 april 2027</strong>.</p></div><form className="form" onSubmit={submit}><div className="field"><label htmlFor="name">Namn <span className="req">*</span></label><input id="name" name="name" value={form.name} onChange={update} required /></div><div className="field"><label>Kommer du? <span className="req">*</span></label><div className="attend">{[['ja', 'Ja, gärna'], ['nej', 'Tyvärr inte']].map(([value, label]) => <label key={value}><input type="radio" name="attending" value={value} checked={form.attending === value} onChange={update} /><span className="opt">{label}</span></label>)}</div></div>{form.attending === 'ja' && <div className="field"><label htmlFor="mealChoice">Matval eller specialkost</label><input id="mealChoice" name="mealChoice" value={form.mealChoice} onChange={update} placeholder="Till exempel vegetarisk eller allergi" /></div>}<div className="field"><label htmlFor="notes">Hälsning eller övriga önskemål</label><textarea id="notes" name="notes" value={form.notes} onChange={update} /></div><button className="btn form__submit" disabled={status === 'sending'}>{status === 'sending' ? 'Skickar…' : 'Skicka OSA'}</button>{status === 'success' && <p className="form-message success" role="status">Tack! Vi har tagit emot din OSA.</p>}{status === 'error' && <p className="form-message error" role="alert">Något gick fel. Försök igen eller kontakta oss via mejl.</p>}</form></div></section>;
}
